name: Create new tag

on:
  # Allow pushes to main to trigger
  push:
    branches: [main]

# Sets up concurrency to ensure that only one job or workflow using the same concurrency group will run at a time.
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  push:
    name: Create tag

    # Specify the job to run on the latest Ubuntu version
    runs-on: ubuntu-latest

    # Permissions for the job
    permissions:
      contents: write

    # Only run this job if the branch is main
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      # https://github.com/actions/checkout
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: "0"
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}

      # Bump version and create a new git tag
      # https://github.com/anothrNick/github-tag-action
      - name: Bump version and push tag
        id: tag
        uses: anothrNick/github-tag-action@f278d49d30cdd8775cc3e7dd00b5ee11686ee297 # v1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: 'true'
          INITIAL_VERSION: '1.0.0'
          DEFAULT_BUMP: 'patch'